import { LegalPageLayout } from "@/components/layout/LegalPageLayout";

export const metadata = { title: "Terms and Conditions | Hammet" };

const content = `
**Effective: 26 June 2026**

These Terms and Conditions ("Terms") govern access to and use of the Hammet platform ("Platform") provided by HammetLTD  (collectively, "HammetLTD," "Hammet," "we," "us," or "our"). Please read these Terms carefully before allowing any student to access the Platform.

By registering a school, enrolling students, or using the Platform in any capacity, the School (as defined below) agrees to be bound by these Terms on behalf of itself, its staff, and its enrolled students.

**_These Terms may be amended from time to time. If we make material changes, we will notify Schools at least 30 days before the changes take effect, as described in Section 19. Continued use of the Platform after the effective date of any change means the School accepts the updated Terms._**

# 1. Definitions
In these Terms, the following terms have the meanings assigned below.
- "Platform" means the Hammet AI literacy learning platform, including its offline-first Progressive Web App, the HammetLTD Digital Passport, teacher facilitation system, and all associated content, tools, and services.
- "School" means the secondary school that has entered into a licensing agreement with HammetLTD for access to the Platform.
- "Student" means any learner enrolled on the Platform by or on behalf of a School.
- "Teacher" means any member of school staff authorised by the School to facilitate lessons using the Platform.
- "School Administrator" means the staff member(s) authorised by the School to manage student and teacher accounts on the Platform.
- "Digital Passport" means the student's cumulative digital learning portfolio maintained on the Platform.
- "Credential" means the Hammet Digital Foundations Credential issued to eligible students upon programme completion.
- "Content" means all curriculum materials, lesson bodies, videos, tasks, assessments, and learning resources available on the Platform.
- "Activity Materials" means all data, responses, submissions, and other materials generated by Students through their use of the Platform's educational activities, excluding original creative work covered by Section 7.2.
- "Licence Fee" means the fee payable by the School as agreed in the applicable licensing agreement.
- "Partner Service" means any optional third-party service that HammetLTD may make available to Schools or Students through the Platform's ecosystem, as described in Section 8A.

# 2. Parties and Applicable Entities
The Platform is operated by Hammet Ltd, a company incorporated in the Federal Republic of Nigeria. Schools contracting for services delivered in Nigeria will primarily transact with Hammet Ltd.

# 3. Nature of Agreement
## 3.1 B2B Licensing
The Platform is licensed exclusively to Schools on a business-to-business basis. Students and parents do not enter into any direct contractual relationship with HammetLTD in connection with the School's licence to use the Platform. The School is solely responsible for ensuring that students access and use the Platform in accordance with these Terms.
For clarity, this does not prevent a Student, parent, or guardian from entering into a separate, direct relationship with HammetLTD in respect of any other product or service that HammetLTD offers on a business-to-consumer basis, outside of the School's licence under these Terms. Any such direct relationship will be governed by its own separate terms and is not affected by, or dependent on, the School's licensing agreement with HammetLabs.
## 3.2 School as Primary Responsible Party
By activating a school account, the School represents and warrants that:
- It has the authority to bind students to these Terms through its institutional capacity as a school.
- It has obtained all necessary consents from parents or guardians, as required by applicable Nigerian law, including but not limited to the Nigeria Data Protection Act 2023 (NDPA), for the collection, processing, and storage of student data as described in the Privacy Policy.
- It will implement and enforce appropriate safeguarding measures to govern student use of the Platform.

# 4. School Representations and Warranties
In addition to the representations made in Section 3.2, the School represents and warrants to HammetLTD that:
- It is a duly recognised educational institution, lawfully operating under the laws of its jurisdiction, with full power and authority to enter into and perform its obligations under these Terms.
- Any individual signing on the School's behalf, including a School Administrator, has the actual authority to bind the School to these Terms.
- Its access to and use of the Platform, and that of its Teachers and Students, will at all times comply with these Terms and with all applicable laws, rules, and regulations of the Federal Republic of Nigeria and any other relevant jurisdiction.
- All information it provides to HammetLTD in connection with registration, including details about the School, its Teachers, and its Students, is accurate, current, and complete.
- It will promptly notify HammetLTD of any material change to information previously provided, including changes to its designated School Administrator.
- It is not subject to any sanction, restriction, or prohibition under Nigerian or applicable international law that would prevent it from lawfully entering into this Agreement.

**_These representations apply to the School as the contracting party. Where Teachers or School Administrators act on the School's behalf, the School remains responsible for ensuring their conduct complies with these Terms._**

# 5. Licence Grant and Restrictions
## 5.1 Licence Grant
Subject to the School's payment of the applicable Licence Fee and compliance with these Terms, HammetLTD grants the School a non-exclusive, non-transferable, revocable licence to:
- Access and use the Platform for the School's own internal educational purposes.
- Allow enrolled Students and authorised Teachers to access Platform Content during the applicable licence period.
- Download offline Content modules to school-authorised or student-owned devices for use within the Platform's offline-first framework.
## 5.2 Restrictions
The School shall not, and shall ensure that Students and Teachers do not:
- Copy, reproduce, distribute, or publicly display Platform Content outside of the Platform environment.
- Sublicence, sell, resell, transfer, assign, or otherwise make the Platform available to any third party.
- Modify, adapt, reverse-engineer, decompile, or create derivative works from any part of the Platform.
- Use any data mining, robots, scraping, or similar automated method to extract Content or data from the Platform.
- Use the Platform for any purpose other than legitimate educational use within the School.
- Share login credentials between multiple users.
- Use the Platform in any manner that violates applicable Nigerian law or any other applicable law.

# 6. Accounts, Access, and Security
## 6.1 School Account
The School Administrator is responsible for creating and managing all accounts on the Platform, including enrolling students, assigning teachers, and maintaining accurate records.
## 6.2 Student Accounts
Students access the Platform through accounts created by the School Administrator. Students under the age of 13 may only access the Platform through school-managed accounts. The School is responsible for ensuring that student accounts are used solely by the named student.
## 6.3 Personal AI Tool Accounts
The Platform curriculum may direct Students to use third-party AI tools such as ChatGPT, Gemini, or Perplexity using a free account. These tools are owned and operated independently of HammetLTD, as further addressed in Section 13A.
## 6.4 Security
The School is responsible for maintaining the confidentiality of all login credentials and for any activity that occurs under its accounts. The School must notify HammetLTD immediately upon becoming aware of any unauthorised access or security breach.

# 7. Licence Fees and Payment
## 7.1 Licence Fee
The School agrees to pay the Licence Fee in accordance with the applicable licensing agreement. HammetLTD may revise its pricing for future licence periods, with notice provided in accordance with Section 19.
## 7.2 Pilot Programme
Schools participating in an approved pilot programme receive free access for the agreed pilot cohort and term, as set out in the applicable Pilot Programme Agreement. Pilot access does not constitute a permanent waiver of Licence Fees. Conversion to a paid licence will be required for continued access after the pilot term.
## 7.3 Payment Terms
Licence Fees are due in accordance with the payment schedule in the applicable licensing agreement. HammetLTD reserves the right to suspend Platform access if fees remain unpaid beyond the agreed grace period.
## 7.4 Refunds
Licence Fees are non-refundable except where HammetLTD has materially failed to deliver the Platform in accordance with these Terms and fails to remedy such failure within 30 days of written notice.

# 8. Content and Intellectual Property
## 8.1 Ownership
All Platform Content, including the curriculum, lesson bodies, design, structure, Digital Passport framework, and credential system, is the exclusive intellectual property of HammetLTD and is protected under applicable copyright and intellectual property laws of Nigeria and the United States.
## 8.2 Student-Generated Content
Students retain ownership of original work they produce through the Platform, including written reflections, creative projects, and submissions stored in the Digital Passport. By submitting content through the Platform, Students and Schools grant HammetLTD a non-exclusive, royalty-free licence to store, display, and use such content for the purpose of operating the Platform, issuing Credentials, and improving the Platform's educational quality.
## 8.3 Activity Materials
As between the School and HammetLTD, Activity Materials generated through the Platform's structured educational activities (as distinct from original creative work under Section 8.2) are owned by HammetLTD and may be used by HammetLTD to operate, maintain, and improve the Platform, including for the purposes described in Section 4 of the Privacy Policy.
## 8.4 Prohibited Use of Content
The School shall not reproduce, extract, or distribute HammetLTD curriculum materials, lesson plans, or assessment frameworks outside the Platform without prior written consent from HammetLTD.

# 8A. Partner Services
From time to time, HammetLTD may make available optional Partner Services through the Platform's ecosystem, such as study placement support, enrichment programmes, or other complementary offerings provided by third-party organisations.
- Partner Services are entirely optional and are not a required part of the core Platform licence.
- Where a School or Student chooses to engage with a Partner Service, that engagement is governed by separate terms between the Student or School and the relevant third-party provider, and HammetLTD is not a party to that arrangement.
- HammetLTD does not guarantee the availability, outcome, or suitability of any Partner Service and is not responsible for the acts or omissions of any third-party provider.
- HammetLTD may introduce, modify, or discontinue access to any Partner Service at its sole discretion and at any time.

# 9. The Digital Passport and Credential
## 9.1 Digital Passport
The Digital Passport is a cumulative record of each student's learning journey on the Platform. It is maintained by HammetLTD and accessible to the student and parent(s).
## 9.2 Credential Issuance
The HammetLTD Digital Foundations Credential is issued directly by HammetLTD to Students who complete the full SSS3 programme and meet the applicable completion standards. Verification of a Credential is handled by HammetLTD directly. The Credential is verifiable and shareable with universities, scholarship bodies, and employers.
## 9.3 Credential Accuracy
HammetLTD makes reasonable efforts to ensure Credential records are accurate. The School is responsible for ensuring that student completion data submitted to the Platform is truthful and accurate.

# 10. Acceptable Use
Our goal is to create a safe, positive, and productive learning experience for every Student on the Platform. To protect that experience, the School agrees to ensure that the Platform is used only for lawful, legitimate educational purposes, and that the conduct described below is never permitted.
## 10.1 Prohibited Conduct
The School shall ensure that no Student, Teacher, or School Administrator, in connection with use of the Platform:
- Submits false, deceptive, plagiarised, or dishonestly obtained work to the Platform.
- Uploads, transmits, or submits any content that is libelous, defamatory, abusive, threatening, harassing, hateful, sexually explicit, obscene, or otherwise harmful to minors.
- Uploads or transmits content that infringes the copyright, trademark, privacy, or other rights of any third party.
- Bullies, harasses, intimidates, or discriminates against another Student, Teacher, or user of the Platform.
- Attempts to gain unauthorised access to another user's account, to HammetLTD systems, or to any part of the Platform not intended for that user.
- Collects, harvests, or attempts to extract the personal data of other users of the Platform.
- Impersonates any person or entity, or misrepresents an affiliation with any person or entity, in connection with use of the Platform.
- Uses the Platform to distribute spam, malware, or any other harmful or disruptive code.
- Uses the Platform in any way that disrupts, damages, or impairs the Platform's infrastructure, security, or the experience of other users.
- Engages in any conduct that, in HammetLTD' reasonable judgment, is objectionable, exposes HammetLTD or its users to harm or liability of any kind, or is otherwise inconsistent with the educational purpose of the Platform.
## 10.2 Enforcement
HammetLTD reserves the right to investigate any suspected violation of this Section and to suspend or terminate any account found to be in breach, without prior notice where the breach is serious or ongoing. Where appropriate, HammetLTD will inform the relevant School Administrator of any action taken against a Student or Teacher account.
## 10.3 Reporting
If a School becomes aware of conduct that may violate this Section, it should notify HammetLTD promptly using the contact details in Section 21.

# 11. Safeguarding
HammetLTD is committed to the safety and wellbeing of all students who use the Platform. The Platform is designed to be age-appropriate for secondary school students from JSS1 to SSS3. The School is responsible for implementing its own safeguarding policies in relation to student use of the Platform, including policies governing internet use and third-party AI tool access. HammetLTD will cooperate with any lawful safeguarding investigation involving Platform activity.

# 12. Availability and Service
## 12.1 Offline-First Design
The Platform is designed to support learning in environments with unreliable internet access. Once the application is installed and a lesson has been opened, that lesson remains available on the same device for offline access. Student work is also saved locally on the device, allowing students to continue their learning even without an internet connection. When connectivity is restored, locally saved work is automatically synchronized with the Platform.
Some features, including downloading new lessons, accessing content that has not previously been opened on the device, and other internet-dependent services, require an active internet connection. HammetLTD does not guarantee uninterrupted availability of these online features but will use commercially reasonable efforts to maintain Platform availability.
## 12.2 Maintenance
HammetLTD may carry out maintenance, updates, or upgrades to the Platform at any time. Where possible, HammetLTD will provide advance notice of significant downtime. Routine maintenance will be scheduled to minimise disruption to school hours.
## 12.3 No Guarantee of Specific Outcomes
HammetLTD does not guarantee that use of the Platform will result in any particular academic outcome, credential attainment, or career result for any individual student. The Platform is an educational tool, and student outcomes depend on individual engagement and school facilitation.

# 13. Disclaimer of Warranties
The Platform is provided on an "as is" and "as available" basis. To the fullest extent permitted by applicable law, HammetLTD disclaims all warranties, express or implied, including without limitation warranties of merchantability, fitness for a particular purpose, and non-infringement. HammetLTD does not warrant that the Platform will be error-free, secure, or continuously available.

# 13A. AI Tools and Accuracy Disclaimer
The Hammet curriculum is built around teaching Students to use artificial intelligence tools critically, safely, and responsibly. As part of this, Students may be directed to use third-party AI tools referenced in Section 6.3.
- Outputs generated by any AI tool, whether accessed through or referenced by the Platform, may at times be inaccurate, incomplete, biased, or otherwise unreliable. This is an inherent characteristic of current AI technology and not a defect specific to the Platform.
- HammetLTD does not warrant the accuracy, completeness, or reliability of any output generated by a third-party AI tool, and is not responsible for any decision made or action taken by a Student, Teacher, or School in reliance on such output.
- Part of the Platform's educational purpose is to teach Students to recognise these limitations, verify information independently, and avoid overdependence on AI-generated answers, consistent with HammetLTD' Responsible Scaling Policy.
- The School is responsible for reinforcing this guidance and for appropriate supervision of Student use of any third-party AI tool, as set out in Section 11.

# 14. Limitation of Liability
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HAMMETLTD SHALL NOT BE LIABLE TO THE SCHOOL OR ANY THIRD PARTY CLAIMING THROUGH THE SCHOOL, WHETHER BASED IN CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES ARISING OUT OF OR RELATING TO THESE TERMS OR THE PLATFORM, INCLUDING BUT NOT LIMITED TO LOSS OF USE, LOSS OF DATA, LOSS OF PROFITS, OR BUSINESS INTERRUPTION, EVEN IF HAMMETtLTD HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HAMMETLTD' TOTAL AGGREGATE LIABILITY TO THE SCHOOL UNDER OR IN CONNECTION WITH THESE TERMS, FOR ANY CAUSE WHATSOEVER, SHALL NOT EXCEED THE TOTAL LICENCE FEES PAID BY THE SCHOOL TO HAMMETLTD IN THE SIX MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM. THIS IS AN AGGREGATE LIMIT, AND THE EXISTENCE OF MORE THAN ONE CLAIM WILL NOT INCREASE THIS LIMIT. WHERE A SCHOOL IS PARTICIPATING IN A FREE PILOT UNDER SECTION 7.2, THIS LIABILITY CAP SHALL BE A NOMINAL AMOUNT REASONABLY DETERMINED BY HAMMETLTD, REFLECTING THE ABSENCE OF ANY LICENCE FEE PAID.

The School acknowledges and agrees that HammetLTD has set its Licence Fees, and structured its free pilot programme, in reliance on the limitations of liability set out in this Section. These limitations reflect a reasonable allocation of risk between the parties and form an essential basis of the bargain between HammetLTD and the School. The School agrees that these limitations will survive even if a remedy is found to have failed its essential purpose.

Nothing in this Section limits or excludes either party's liability for death or personal injury caused by its own negligence, for fraud or fraudulent misrepresentation, or for any other liability that cannot lawfully be limited or excluded under the laws of the Federal Republic of Nigeria.

# 15. Indemnification
The School agrees to defend, indemnify, and hold harmless HammetLTD, and its directors, officers, employees, contractors, agents, successors, and assigns, from and against any and all losses, claims, causes of action, liabilities, damages, and expenses (including reasonable legal fees) arising out of or relating to:
- The School's breach of these Terms, including any breach by a Teacher, School Administrator, or Student acting under the School's account.
- Any false or misleading representation made by the School to HammetLTD, whether under these Terms or otherwise.
- The School's use of the Platform in violation of applicable law.
- Any claim by a Student, parent, or guardian arising from the School's failure to obtain any consent required under Section 3.2 or applicable law.
- Any third-party claim arising from content submitted to the Platform by the School, its Teachers, or its Students, including any claim that such content infringes the rights of a third party.

HammetLTD reserves the right, at its own expense, to assume the exclusive defence and control of any matter otherwise subject to indemnification by the School, in which event the School agrees to cooperate with HammetLTD in asserting any available defences.

# 16. Term and Termination
## 16.1 Term
These Terms remain in effect for the duration of the licensing agreement between the School and HammetLTD and any renewal thereof.
## 16.2 Termination by HammetLTD
HammetLTD may suspend or terminate the School's access to the Platform immediately upon written notice if the School:
- Materially breaches these Terms and fails to remedy such breach within 14 days of notice.
- Fails to pay Licence Fees within the agreed grace period.
- Engages in conduct that HammetLTD reasonably determines to be harmful to students, other users, or the Platform.
## 16.3 Termination by the School
The School may terminate these Terms in accordance with the termination provisions of the applicable licensing agreement.
## 16.4 Effect of Termination
Upon termination, the School's licence becomes inactive.
## 16.5 Survival
Sections 1 (Definitions), 8 (Content and Intellectual Property), 9 (The Digital Passport and Credential), 13 (Disclaimer of Warranties), 13A (AI Tools and Accuracy Disclaimer), 14 (Limitation of Liability), 15 (Indemnification), 17 (Modifications to Terms), 18 (Governing Law and Dispute Resolution), and 19 (General) shall survive any termination or expiry of these Terms.

# 17. Modifications to Terms
HammetLTD reserves the right to modify these Terms at any time. Schools will be notified of material changes at least 30 days before they take effect. Continued use of the Platform after the effective date of any modification constitutes acceptance of the revised Terms.

# 18. Governing Law and Dispute Resolution
These Terms are governed by and construed in accordance with the laws of the Federal Republic of Nigeria. Any dispute arising out of or in connection with these Terms shall first be subject to good-faith negotiation between the parties. If not resolved within 30 days, disputes shall be submitted to mediation in Lagos, Nigeria, before any formal legal proceedings are commenced.

# 19. General
## 19.1 Entire Agreement
These Terms, together with the applicable licensing agreement and Privacy Policy, constitute the entire agreement between HammetLTD and the School relating to the Platform, and supersede any prior discussions, representations, or agreements relating to the same subject matter.
## 19.2 Severability
If any provision of these Terms is found to be unenforceable, the remaining provisions shall remain in full force and effect.
## 19.3 Waiver
Failure to enforce any provision of these Terms shall not constitute a waiver of that provision.
## 19.4 Assignment
The School may not assign its rights or obligations under these Terms without HammetLTD's prior written consent. HammetLTD may assign these Terms in connection with a merger, acquisition, corporate reorganisation, or sale of substantially all of its relevant assets.
## 19.5 Notices
Any formal notice required under these Terms must be sent in writing to the contact details provided by each party, including by email, and will be deemed received in accordance with standard electronic communication practice.

# 20. Trademarks
"Hammet," "HammetLTD," the Hammet logo, and all other trademarks, service marks, graphics, and logos used in connection with the Platform are trademarks of HammetLTD or its licensors. Access to and use of the Platform does not grant the School, its Teachers, or its Students any right or licence to reproduce or otherwise use any HammetLTD trademark, service mark, graphic, or logo, except as expressly authorised in writing by HammetLTD.

# 21. Contact
For questions regarding these Terms, please contact:

**Hammet Ltd**  
**Email:** [admin@hammetlabs.com](mailto:admin@hammetlabs.com)  
**Website:** [hammet.hammetlabs.com](https://hammet.hammetlabs.com)`;

export default function TermsAndConditionsPage() {
  return (
    <LegalPageLayout title="Terms and Conditions" lastUpdated="June 2026" content={content} />  
  );
}